/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.lr.goldisan.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.ShardedModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Company service. Represents a row in the &quot;lr_Company&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.lr.goldisan.model.impl.CompanyModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.lr.goldisan.model.impl.CompanyImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Company
 * @generated
 */
@ProviderType
public interface CompanyModel extends BaseModel<Company>, ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a company model instance should use the {@link Company} interface instead.
	 */

	/**
	 * Returns the primary key of this company.
	 *
	 * @return the primary key of this company
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this company.
	 *
	 * @param primaryKey the primary key of this company
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this company.
	 *
	 * @return the uuid of this company
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this company.
	 *
	 * @param uuid the uuid of this company
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the company ID of this company.
	 *
	 * @return the company ID of this company
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this company.
	 *
	 * @param companyId the company ID of this company
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the company name of this company.
	 *
	 * @return the company name of this company
	 */
	@AutoEscape
	public String getCompanyName();

	/**
	 * Sets the company name of this company.
	 *
	 * @param companyName the company name of this company
	 */
	public void setCompanyName(String companyName);

	/**
	 * Returns the registration ID of this company.
	 *
	 * @return the registration ID of this company
	 */
	public long getRegistrationId();

	/**
	 * Sets the registration ID of this company.
	 *
	 * @param registrationId the registration ID of this company
	 */
	public void setRegistrationId(long registrationId);

	/**
	 * Returns the email of this company.
	 *
	 * @return the email of this company
	 */
	@AutoEscape
	public String getEmail();

	/**
	 * Sets the email of this company.
	 *
	 * @param email the email of this company
	 */
	public void setEmail(String email);

	/**
	 * Returns the tax ID of this company.
	 *
	 * @return the tax ID of this company
	 */
	public long getTaxId();

	/**
	 * Sets the tax ID of this company.
	 *
	 * @param taxId the tax ID of this company
	 */
	public void setTaxId(long taxId);

	/**
	 * Returns the phone number of this company.
	 *
	 * @return the phone number of this company
	 */
	public long getPhoneNumber();

	/**
	 * Sets the phone number of this company.
	 *
	 * @param phoneNumber the phone number of this company
	 */
	public void setPhoneNumber(long phoneNumber);

	/**
	 * Returns the gst of this company.
	 *
	 * @return the gst of this company
	 */
	public long getGst();

	/**
	 * Sets the gst of this company.
	 *
	 * @param gst the gst of this company
	 */
	public void setGst(long gst);

	/**
	 * Returns the address of this company.
	 *
	 * @return the address of this company
	 */
	@AutoEscape
	public String getAddress();

	/**
	 * Sets the address of this company.
	 *
	 * @param address the address of this company
	 */
	public void setAddress(String address);

	@Override
	public Company cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}