/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.lr.goldisannew.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Store service. Represents a row in the &quot;lr_Store&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.lr.goldisannew.model.impl.StoreModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.lr.goldisannew.model.impl.StoreImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Store
 * @generated
 */
@ProviderType
public interface StoreModel extends BaseModel<Store> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a store model instance should use the {@link Store} interface instead.
	 */

	/**
	 * Returns the primary key of this store.
	 *
	 * @return the primary key of this store
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this store.
	 *
	 * @param primaryKey the primary key of this store
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this store.
	 *
	 * @return the uuid of this store
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this store.
	 *
	 * @param uuid the uuid of this store
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the store ID of this store.
	 *
	 * @return the store ID of this store
	 */
	public long getStoreId();

	/**
	 * Sets the store ID of this store.
	 *
	 * @param storeId the store ID of this store
	 */
	public void setStoreId(long storeId);

	/**
	 * Returns the branch ID of this store.
	 *
	 * @return the branch ID of this store
	 */
	public long getBranchId();

	/**
	 * Sets the branch ID of this store.
	 *
	 * @param branchId the branch ID of this store
	 */
	public void setBranchId(long branchId);

	/**
	 * Returns the branch name of this store.
	 *
	 * @return the branch name of this store
	 */
	@AutoEscape
	public String getBranchName();

	/**
	 * Sets the branch name of this store.
	 *
	 * @param branchName the branch name of this store
	 */
	public void setBranchName(String branchName);

	/**
	 * Returns the address of this store.
	 *
	 * @return the address of this store
	 */
	@AutoEscape
	public String getAddress();

	/**
	 * Sets the address of this store.
	 *
	 * @param address the address of this store
	 */
	public void setAddress(String address);

	/**
	 * Returns the contact number of this store.
	 *
	 * @return the contact number of this store
	 */
	public long getContactNumber();

	/**
	 * Sets the contact number of this store.
	 *
	 * @param contactNumber the contact number of this store
	 */
	public void setContactNumber(long contactNumber);

	@Override
	public Store cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}